name: Publicar Librería de React en GitHub Packages

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jmurga97'
        
      - name: Configurar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependencias con Bun
        run: bun install --frozen-lockfile

      - name: Compilar la librería de React
        run: bun run build

      - name: Verificar archivos compilados
        run: |
          ls -la dist/
          echo "Contenido del package.json:"
          cat package.json | jq '.name, .version, .publishConfig'

      - name: Publicar en GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
