name: Publicar Librería de React en GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Configurar registro de GitHub Packages
        run: |
          echo "@jmurga97:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Instalar dependencias con Bun
        run: bun install --frozen-lockfile

      - name: Compilar la librería de React
        run: bun run build

      - name: Publicar en GitHub Packages
        run: bun publish --access public
